name: Publish
on: 
  workflow_dispatch:

jobs:
  publish_addon:
    runs-on: ubuntu-latest
    steps:
    - name: Check out dev repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false

    - name: Log in to the Container registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Addon Image
      uses: home-assistant/builder@2024.08.02
      with:
        args: |
          --all \
          --target cheerlights \
          --image {arch}-lametric-cheerlights-addon \
          --docker-hub "ghcr.io/${{ github.repository_owner }}" \
